"""criar_db

Revision ID: 58676ae21993
Revises: 
Create Date: 2023-08-27 20:04:49.587214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58676ae21993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_usuario')
    # ### end Alembic commands ###
